# Generated by Django 3.2 on 2022-04-14 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('tipo', models.CharField(choices=[('Interna', 'Interna'), ('Externa', 'Externa')], max_length=20)),
                ('dirigido_a', models.CharField(max_length=120)),
                ('objetivo', models.TextField(max_length=500)),
                ('temario', models.TextField(max_length=1000)),
                ('documento', models.FileField(blank=True, upload_to='rrhh/docs_cap')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('estatus', models.CharField(max_length=1)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Cap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(auto_now=True)),
                ('fecha', models.DateTimeField()),
                ('impartido_por', models.CharField(blank=True, max_length=150)),
                ('lugar', models.CharField(max_length=120)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.capacitacion')),
                ('convocados', models.ManyToManyField(to='rrhh.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Ejecuta_Cap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_impartido', models.DateField()),
                ('participantes', models.ManyToManyField(to='rrhh.Empleado')),
                ('plan_cap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rrhh.plan_cap')),
            ],
        ),
        migrations.CreateModel(
            name='Area_RH',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=20, verbose_name='Area')),
                ('integrantes', models.ManyToManyField(to='rrhh.Empleado')),
            ],
        ),
    ]
